#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  export KITCHEN_YAML="$(pwd)/.module/fogg-tf/kitchen.yml"
  exec fogg shell kitchen "$@"
}

source sub "$BASH_SOURCE" "$@"
