#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_config="$1"; shift
  local nm_profile="$1"; shift

  set -- $(cat "$pth_config" | jq -r --arg profile "$nm_profile" '.[$profile] | "\(.op) \(.mfa)"')

  local nm_vault="$1"; shift
  local nm_mfa="$1"; shift

  exec op assume "$nm_vault" imma totp "$nm_mfa"
}

source sub "$BASH_SOURCE" "$@"
