#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  ln -nfs ../module .
  if [[ -f main.tf ]]; then
    tf init -backend=false
    tf validate -check-variables=false
  fi
}

source sub "$BASH_SOURCE" "$@"
