#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_profile
  local nm_user

  if [[ -n "${1:-}" ]]; then
    case "$1" in
      *@*)
        nm_user="${1%%@*}"
        nm_profile="${1##*@}"
        shift
        ;;
      *)
        nm_profile="$1"; shift
        ;;
    esac
  fi

  if [[ -z "${nm_user:-}" ]]; then
    nm_user="$(cat "${BOARD_PATH}/.aws/assume" | jq -r --arg vault "$nm_profile" '.[$vault].mfa | split("/")[-1]')"
  fi

  if [[ "$#" == 0 ]]; then
    set -- bash -l
  fi

  export CONTEXT_ORG="$nm_profile"
  export AWS_SESSION_EXPIRATION="$(date -d "1 hour" -u +"%Y-%m-%dT%H:%M:%SZ")"

  unset AWS_SESSION_TOKEN AWS_VAULT AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID AWS_SECURITY_TOKEN
  exec aws vault exec "$nm_profile" --assume-role-ttl=60m -m "$(imma totp "$nm_user")" -- "$@"
}

source sub "$BASH_SOURCE" "$@"
