#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize
  
  case "$#" in
    0)
      echo "ERROR: need to specific profile and app name" 1>&2
      return 1
      ;;
    1)
      echo "ERROR: need to specific app name" 1>&2
      return 1
      ;;
  esac

  local nm_profile="$1"; shift
  local nm_app="$1"; shift

  if [[ "$#" == 0 ]]; then
    set -- bash -il
  fi

  exec fogg assume "$nm_profile" chamber exec "$nm_app" -- "$@"
}

source sub "$BASH_SOURCE" "$@"
