#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize
  
  case "$#" in
    0)
      echo "ERROR: need to specific profile, app name optional" 1>&2
      return 1
      ;;
  esac

  local nm_profile="$1"; shift
  local nm_app="${1:-}"

  if [[ -n "${nm_app}" ]]; then
    shift
  fi

  if [[ "$#" == 0 ]]; then
    set -- "$SHELL"
  fi

  exec fogg assume "$nm_profile" ${nm_app:+chamber exec "${nm_app}"} -- "$@"
}

source sub "$BASH_SOURCE" "$@"
