#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" == 0 ]]; then
    set -- .
  fi

  for a in "$@"; do
    pushd "$a"
    ln -nfs ../.module .
    if [[ "$(ls -d *.tf *.tf.json 2>/dev/null | wc -l | awk '{print $1}')" -gt 0 ]]; then
      tf check
    fi
    popd
  done
}

source sub "$BASH_SOURCE" "$@"
