#!/usr/bin/env bash

function main {
  fogg fn package
  sam local generate-event api -r "/$(cut -d/ -f4 .fogg-name)/$(cut -d/ -f6 .fogg-name)" | sam local invoke -t sam.json | jq '.body |= fromjson'
}

source sub "$BASH_SOURCE" "$@"
