#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_profile
  local nm_user

  if [[ -n "${1:-}" ]]; then
    case "$1" in
      *@*)
        nm_user="${1%%@*}"
        nm_profile="${1##*@}"
        shift
        ;;
      *)
        nm_profile="$1"; shift
        ;;
    esac
  fi

  if [[ -z "${nm_user:-}" ]]; then
    nm_user="$(cat "${AWS_CONFIG_FILE%/config}/assume" | jq -r --arg vault "$nm_profile" '.[$vault].mfa | split("/")[-1]')"
  fi

  if [[ "$#" == 0 ]]; then
    set -- bash -l
  fi

  export AWS_SESSION_EXPIRATION="$(gdate -d "1 hour" -u +"%Y-%m-%dT%H:%M:%SZ")"

  export CONTEXT_ORG="$nm_profile"
  unset AWS_SESSION_TOKEN AWS_VAULT AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID AWS_SECURITY_TOKEN
  
  aws vault list >/dev/null || true
  if ! aws vault list --sessions | egrep "^${CONTEXT_ORG} session" >/dev/null; then
    local code="$("$CONTEXT_ORG" code)"
    aws vault exec "$nm_profile" --assume-role-ttl=60m ${code:+-m "${code}"} -- true
    case "$(uname -s)" in
      Darwin)
        aws vault exec "$nm_profile" --assume-role-ttl=60m -- true
        ;;
    esac
  fi

  export AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
  export AWS_DEFAULT_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"

  local tmp_env="$(mktemp -t XXXXXX)"
  trap "$(printf 'rm -f %q' "$tmp_env")" EXIT

  case "$(uname -s)" in
    Darwin)
      aws vault exec "$nm_profile" --assume-role-ttl=60m -- \
        env
      ;;
    *)
      env $("$nm_profile" gpg --duration-seconds 3600 | jq -r '.Credentials | "AWS_ACCESS_KEY_ID=\(.AccessKeyId) AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) AWS_SESSION_TOKEN=\(.SessionToken) AWS_EXPIRATION=\(.Expiration)"') \
        env
      ;;
  esac | grep ^AWS_ | sed 's#^#export #' > "$tmp_env"

  if [[ -s "$tmp_env" ]]; then
    source "$tmp_env"
    exec "$@"
  else
    aws vault exec "$nm_profile" --assume-role-ttl=60m -- false
  fi
  rm -f "$tmp_env"

}

source sub "$BASH_SOURCE" "$@"
