#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" == 0 ]]; then
    set -- "$SHELL"
  fi

  eval $(fogg account tf env fogg_ | perl -pe 's{^}{export };s{=}{="};s{$}{"}' | sort)
  exec fogg account "$@"
}

source sub "$BASH_SOURCE" "$@"
