#!/usr/bin/env bash

function _fogg_cli_profile {
  local shome="${_fogg_cli_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  FOGG_CLI_VERSION='0.0.1'
}

_fogg_cli_profile
