#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_cli="0.0.1"
  jq -n --arg fogg_cli "$ver_fogg_cli" '{fogg_cli: $fogg_cli}'
}

version "$@"
